name: clqr
params:                    # Physical parameters
  g: 9.8                   # Gravity acceleration (m/s^2)
  m_c: 1.0                 # Mass of cart (kg)
  m_p: 0.1                 # Mass of pole (kg)
  l: 0.5                   # Half-length of the pole (m)
  force_mag: 10.0          # Nominal force magnitude (N)
  Q: [0.2, 0.2, 2.0, 0.5]  # State cost diagonal weight (continuous-time)
  R: [1.5]                 # Control cost weight (continuous-time)
runner_args:
  max_episode_steps: 10000
  dt: 0.02
  force_mag: 10.0
  render_mode: human
run_params:
  n_episodes: 1
  max_steps: 1000
  seed_offset: 0
  deadband: 0.0
